package gg.ingot.iron

import gg.ingot.iron.representation.DatabaseDriver
import gg.ingot.iron.serialization.SerializationAdapter
import java.util.Properties
import kotlin.time.Duration
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Duration.Companion.seconds

/**
 * Settings for the Iron connection pool.
 * @author DebitCardz
 * @since 1.2
 */
data class IronSettings(
    /** Minimum active connections in the pool. */
    val minimumActiveConnections: Int = 1,
    /** Maximum connections allowed to be generated by a pool. */
    val maximumConnections: Int = 1,
    /** The timeout for connection polling. */
    val connectionPollTimeout: Duration = 30.seconds,
    /** The driver to use for the connection pool. */
    val driver: DatabaseDriver? = null,
    /** The serialization adapter to use for models. */
    val serialization: SerializationAdapter? = null,
    /** Additional properties to pass into the [java.sql.DriverManager] */
    val driverProperties: Properties? = null
) {
    /** Whether the connection pool is a multi connection pool. */
    val isMultiConnectionPool: Boolean
        get() = minimumActiveConnections > 1 || maximumConnections > 1

    init {
        require(minimumActiveConnections >= 0) { "Minimum active connections must be greater than or equal to 0" }
        require(maximumConnections > 0) { "Maximum connections must be greater than 0" }
        require(minimumActiveConnections <= maximumConnections) { "Minimum active connections must be less than or equal to maximum connections" }
    }
}
